Proposal quotation delivery
NathanGrenier/SOEN-343 pull request #17
Opened 2024-11-12 20:14 UTC by TheMasterProgrammer

Delivery Request features to be merged with the main branch

2024-11-13 02:32 UTC, ImenKhezzar requested changes
You need to pull main into your branch

2024-11-14 01:09 UTC, Crystalz03 requested changes

2024-11-14 01:09 UTC, Crystalz03 commented on packages/client/src/routes/delivery_request.tsx
> +      <Navbar />
You should encapsulate the entire return statement with <> and </> and put the navbar outside the <div className...>

2024-11-14 01:09 UTC, Crystalz03 commented on packages/client/src/routes/delivery_request.tsx
> +    </div>
Same thing at the navbar put the footer outside the div and inside the </>

2024-11-14 01:09 UTC, Crystalz03 commented on packages/client/src/main.tsx
> +    ],
I don't think these should be children elements of the payment page. They should be on the same level as the other pages.

2024-11-14 02:22 UTC, ImenKhezzar approved these changes

2024-11-14 02:37 UTC, Crystalz03 approved these changes

2024-11-14 03:10 UTC, merged